### PR TITLE
Bring in js rules

### LINKED ISSUE #10: Bring in JS Rules
wd_s already has some eslint-based JS rules, we could bring that in here.

### PR DESCRIPTION
**Pull request by aubreypwd**
Fixes #10 — I think this brings in wds_s eslintrc and improves on it, bring in all WP Core jshint rules they use, and rules that aren't inherited by the npm package extended by eslintrc.

- [x] Test in Sublime
- [x] Test in Storm
- [x] Test in Atom
- [x] Get 5 votes 
    - [x] 2 of them from a lead
- [ ] Lead Merge into release

You should be able to checkout the branch on your local repo. Storm and Atom may have different issue and may require contributions.

### CODE REVIEW

**Comment by aubreypwd** [comment]
Once I got eslint setup in Atom I was able to get our rules loaded. Going to update instructions for Atom.

**Comment by JayWood** [comment]
@gregrickaby @coreymcollins I know you guys do a lot more with JavaScript than we do at times, so if one of you peeps could give this your blessing we can move forward.

**Comment by gregrickaby** [comment]
Great work! 👍

**Comment by coreymcollins** [comment]
Going to give this a look this evening - commenting here so I can hold myself to it.  The days keep getting away from me before I get a chance to check this out!

**Pull request merged**
