### PR TITLE
Feature/sass lint

### LINKED ISSUE #21: Bring in wd_s Sass Ruleset
From #10

### PR DESCRIPTION
**Pull request by gregrickaby**
Closes #21 

This brings in the latest `.sass-lint.yml` rules from wd_s.

### CODE REVIEW

**Comment by aubreypwd** [comment]
@gregrickaby I assume this is working in your editor? What editor is that?

**Comment by aubreypwd** [comment]
- [ ] We should also document it's use in editors as well

**Comment by gregrickaby** [comment]
@aubreypwd I've beefed up the SassLint documentation. View it [here](https://github.com/WebDevStudios/WDS-Coding-Standards/blob/bb75da93213d9c1e9e7c88079d835652715cce07/README.md#sasslint-scss-linting):

**Comment by aubreypwd** [comment]
Works in Atom:



The above is not in alpha order.

**Comment by coreymcollins** [comment]
Tested in Sublime as well and things appear to be working as expected!

**Comment by jomurgel** [comment]
Appears to be working in VSCode 👍  

screenshot 2017-10-20 08 40 47
screenshot 2017-10-20 08 41 35

I upvote this bad boy.

**Pull request merged**
